---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Thrust
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Thrust: '0'
  AnyEvent: '0'
  JSON::XS: '0'
  Scalar::Util: '0'
  common::sense: '0'
resources:
  bugtracker: https://github.com/hoytech/Thrust/issues
  repository: git://github.com/hoytech/Thrust.git
version: '0.200'
